# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    # 镜像
    image: mysql
    # 是否重启
    restart: always
    # 环境
    environment:
      # 密码
      MYSQL_ROOT_PASSWORD: 123456

    # 端口
    ports:
      - 3390:3306
    # (this is just an example, not intended to be a production configuration)

    # adminer服务: 就是可视化界面的插件
  adminer:
    # 镜像
    image: adminer
    # 是否重启
    restart: always
    # 端口
    ports:
      - 8090:8080
